import { jsPDF } from 'jspdf';

// Helper function to create and download a file
const downloadFile = (content, filename, mimeType) => {
  const blob = new Blob(content, { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// ==================== WORKOUT EXPORTS ====================

// Export Workout to PDF
export const exportWorkoutToPdf = (workout, userName) => {
  const doc = new jsPDF();
  
  const primaryColor = '#4F46E5';
  const textColor = '#1F2937';
  const mutedColor = '#6B7280';
  
  // Header
  doc.setFillColor(primaryColor);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Workout Details', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by ${userName}`, 105, 30, { align: 'center' });
  
  doc.setTextColor(textColor);
  
  // Workout Name
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(workout.exrciseName || 'Workout', 20, 55);
  
  // Status badge
  const statusColor = workout.status === 'Completed' ? '#10B981' : 
                      workout.status === 'Missed' ? '#EF4444' : '#F59E0B';
  doc.setFillColor(statusColor);
  doc.roundedRect(20, 60, 35, 8, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(workout.status, 37.5, 65.5, { align: 'center' });
  
  // Category
  doc.setTextColor(textColor);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Category: ${workout.category || 'N/A'}`, 20, 78);
  
  // Date
  if (workout.date) {
    doc.text(`Date: ${new Date(workout.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, 86);
  }
  
  // Divider
  doc.setDrawColor(229, 231, 235);
  doc.line(20, 92, 190, 92);
  
  // Details section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Workout Details', 20, 102);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const details = [
    { label: 'Sets', value: workout.sets || 'N/A' },
    { label: 'Reps', value: workout.reps || 'N/A' },
    { label: 'Weight', value: `${workout.weight || 0} kg` },
    { label: 'Duration', value: workout.duration ? `${workout.duration} min` : 'N/A' },
    { label: 'Distance', value: workout.distance ? `${workout.distance} km` : 'N/A' },
    { label: 'Calories Burned', value: workout.caloriesBurned || 'N/A' },
  ];
  
  let yPos = 112;
  details.forEach((detail) => {
    doc.setTextColor(mutedColor);
    doc.text(detail.label, 20, yPos);
    doc.setTextColor(textColor);
    doc.setFont('helvetica', 'bold');
    doc.text(String(detail.value), 70, yPos);
    doc.setFont('helvetica', 'normal');
    yPos += 8;
  });
  
  // Notes section
  if (workout.notes) {
    yPos += 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(textColor);
    doc.text('Notes', 20, yPos);
    
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(mutedColor);
    
    const splitNotes = doc.splitTextToSize(workout.notes, 170);
    doc.text(splitNotes, 20, yPos);
  }
  
  // Footer
  const footerY = 280;
  doc.setDrawColor(229, 231, 235);
  doc.line(20, footerY, 190, footerY);
  doc.setFontSize(8);
  doc.setTextColor(mutedColor);
  doc.text('Generated from R-Fit Fitness App', 105, footerY + 8, { align: 'center' });
  doc.text(new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  }), 105, footerY + 14, { align: 'center' });
  
  doc.save(`workout-${workout.exrciseName || 'details'}-${new Date().toISOString().split('T')[0]}.pdf`);
};

// Export Workout to Word (DOCX format using HTML)
export const exportWorkoutToWord = (workout, userName) => {
  const htmlContent = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8">
      <title>Workout Details - R-Fit Fitness App</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { background-color: #4F46E5; color: white; padding: 20px; text-align: center; }
        .title { font-size: 24px; font-weight: bold; }
        .subtitle { font-size: 14px; }
        .section { margin: 20px 0; }
        .section-title { font-size: 18px; font-weight: bold; color: #4F46E5; border-bottom: 2px solid #4F46E5; padding-bottom: 5px; }
        .detail-row { display: flex; margin: 10px 0; }
        .label { font-weight: bold; width: 150px; color: #6B7280; }
        .value { color: #1F2937; }
        .status { display: inline-block; padding: 4px 12px; border-radius: 12px; color: white; font-size: 12px; }
        .status-completed { background-color: #10B981; }
        .status-missed { background-color: #EF4444; }
        .status-pending { background-color: #F59E0B; }
        .notes { background-color: #F3F4F6; padding: 15px; border-radius: 8px; margin-top: 10px; }
        .footer { margin-top: 40px; text-align: center; color: #6B7280; font-size: 12px; border-top: 1px solid #E5E7EB; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">Workout Details</div>
        <div class="subtitle">Generated by ${userName}</div>
      </div>
      
      <div class="section">
        <h1 style="font-size: 28px; margin-bottom: 10px;">${workout.exrciseName || 'Workout'}</h1>
        <span class="status ${workout.status === 'Completed' ? 'status-completed' : workout.status === 'Missed' ? 'status-missed' : 'status-pending'}">${workout.status}</span>
        <span style="margin-left: 10px; color: #6B7280;">${workout.category || ''}</span>
      </div>
      
      <div class="section">
        <div class="section-title">Workout Details</div>
        <div class="detail-row">
          <span class="label">Sets:</span>
          <span class="value">${workout.sets || 'N/A'}</span>
        </div>
        <div class="detail-row">
          <span class="label">Reps:</span>
          <span class="value">${workout.reps || 'N/A'}</span>
        </div>
        <div class="detail-row">
          <span class="label">Weight:</span>
          <span class="value">${workout.weight || 0} kg</span>
        </div>
        <div class="detail-row">
          <span class="label">Duration:</span>
          <span class="value">${workout.duration ? workout.duration + ' min' : 'N/A'}</span>
        </div>
        <div class="detail-row">
          <span class="label">Distance:</span>
          <span class="value">${workout.distance ? workout.distance + ' km' : 'N/A'}</span>
        </div>
        <div class="detail-row">
          <span class="label">Calories Burned:</span>
          <span class="value">${workout.caloriesBurned || 'N/A'}</span>
        </div>
        ${workout.date ? `
        <div class="detail-row">
          <span class="label">Date:</span>
          <span class="value">${new Date(workout.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
        </div>
        ` : ''}
      </div>
      
      ${workout.notes ? `
      <div class="section">
        <div class="section-title">Notes</div>
        <div class="notes">${workout.notes}</div>
      </div>
      ` : ''}
      
      <div class="footer">
        Generated from R-Fit Fitness App<br>
        ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
      </div>
    </body>
    </html>
  `;
  
  const blob = new Blob([htmlContent], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `workout-${workout.exrciseName || 'details'}-${new Date().toISOString().split('T')[0]}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// Export Workout to CSV
export const exportWorkoutToCsv = (workout, userName) => {
  const headers = ['Field', 'Value'];
  const data = [
    ['Exercise Name', workout.exrciseName || ''],
    ['Status', workout.status || ''],
    ['Category', workout.category || ''],
    ['Sets', workout.sets || ''],
    ['Reps', workout.reps || ''],
    ['Weight (kg)', workout.weight || ''],
    ['Duration (min)', workout.duration || ''],
    ['Distance (km)', workout.distance || ''],
    ['Calories Burned', workout.caloriesBurned || ''],
    ['Date', workout.date ? new Date(workout.date).toLocaleDateString() : ''],
    ['Notes', workout.notes || ''],
    ['Generated By', userName],
    ['Generated Date', new Date().toLocaleDateString()]
  ];
  
  let csvContent = '\uFEFF'; // BOM for UTF-8
  csvContent += headers.join(',') + '\n';
  
  data.forEach(row => {
    const escapedRow = row.map(cell => {
      const cellStr = String(cell);
      if (cellStr.includes(',') || cellStr.includes('"') || cellStr.includes('\n')) {
        return `"${cellStr.replace(/"/g, '""')}"`;
      }
      return cellStr;
    });
    csvContent += escapedRow.join(',') + '\n';
  });
  
  downloadFile([csvContent], `workout-${workout.exrciseName || 'details'}-${new Date().toISOString().split('T')[0]}.csv`, 'text/csv;charset=utf-8');
};

// ==================== NUTRITION EXPORTS ====================

// Export Nutrition to PDF
export const exportNutritionToPdf = (nutrition, userName) => {
  const doc = new jsPDF();
  
  const primaryColor = '#10B981';
  const textColor = '#1F2937';
  const mutedColor = '#6B7280';
  
  // Header
  doc.setFillColor(primaryColor);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Nutrition Details', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by ${userName}`, 105, 30, { align: 'center' });
  
  doc.setTextColor(textColor);
  
  // Food Item Name
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(nutrition.foodItem || 'Nutrition Entry', 20, 55);
  
  // Status badge
  const statusColor = nutrition.status === 'Completed' ? '#10B981' : 
                      nutrition.status === 'Missed' ? '#EF4444' : '#F59E0B';
  doc.setFillColor(statusColor);
  doc.roundedRect(20, 60, 35, 8, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(nutrition.status, 37.5, 65.5, { align: 'center' });
  
  // Meal Type
  doc.setTextColor(textColor);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Meal Type: ${nutrition.mealType || 'N/A'}`, 20, 78);
  
  // Date
  if (nutrition.date) {
    doc.text(`Date: ${new Date(nutrition.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, 86);
  }
  
  // Divider
  doc.setDrawColor(229, 231, 235);
  doc.line(20, 92, 190, 92);
  
  // Nutrition Facts section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Nutritional Information', 20, 102);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const nutritionFacts = [
    { label: 'Calories', value: `${nutrition.calories || 0} kcal` },
    { label: 'Protein', value: `${nutrition.protein || 0}g` },
    { label: 'Carbohydrates', value: `${nutrition.carbs || 0}g` },
    { label: 'Fats', value: `${nutrition.fats || 0}g` },
    { label: 'Fiber', value: `${nutrition.fiber || 0}g` },
    { label: 'Sugar', value: `${nutrition.sugar || 0}g` },
    { label: 'Sodium', value: `${nutrition.sodium || 0}mg` },
  ];
  
  let yPos = 112;
  nutritionFacts.forEach((fact) => {
    doc.setTextColor(mutedColor);
    doc.text(fact.label, 20, yPos);
    doc.setTextColor(textColor);
    doc.setFont('helvetica', 'bold');
    doc.text(fact.value, 80, yPos);
    doc.setFont('helvetica', 'normal');
    yPos += 8;
  });
  
  // Additional Info section
  yPos += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(textColor);
  doc.text('Additional Information', 20, yPos);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const additionalInfo = [
    { label: 'Serving Size', value: nutrition.servingSize || 'N/A' },
    { label: 'Water Intake', value: nutrition.waterIntake ? `${nutrition.waterIntake}L` : 'N/A' },
  ];
  
  yPos += 8;
  additionalInfo.forEach((info) => {
    doc.setTextColor(mutedColor);
    doc.text(info.label, 20, yPos);
    doc.setTextColor(textColor);
    doc.setFont('helvetica', 'bold');
    doc.text(info.value, 80, yPos);
    doc.setFont('helvetica', 'normal');
    yPos += 8;
  });
  
  // Notes section
  if (nutrition.notes) {
    yPos += 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(textColor);
    doc.text('Notes', 20, yPos);
    
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(mutedColor);
    
    const splitNotes = doc.splitTextToSize(nutrition.notes, 170);
    doc.text(splitNotes, 20, yPos);
  }
  
  // Footer
  const footerY = 280;
  doc.setDrawColor(229, 231, 235);
  doc.line(20, footerY, 190, footerY);
  doc.setFontSize(8);
  doc.setTextColor(mutedColor);
  doc.text('Generated from R-Fit Fitness App', 105, footerY + 8, { align: 'center' });
  doc.text(new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  }), 105, footerY + 14, { align: 'center' });
  
  doc.save(`nutrition-${nutrition.foodItem || 'details'}-${new Date().toISOString().split('T')[0]}.pdf`);
};

// Export Nutrition to Word (DOCX format using HTML)
export const exportNutritionToWord = (nutrition, userName) => {
  const htmlContent = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8">
      <title>Nutrition Details - R-Fit Fitness App</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { background-color: #10B981; color: white; padding: 20px; text-align: center; }
        .title { font-size: 24px; font-weight: bold; }
        .subtitle { font-size: 14px; }
        .section { margin: 20px 0; }
        .section-title { font-size: 18px; font-weight: bold; color: #10B981; border-bottom: 2px solid #10B981; padding-bottom: 5px; }
        .detail-row { display: flex; margin: 10px 0; }
        .label { font-weight: bold; width: 180px; color: #6B7280; }
        .value { color: #1F2937; }
        .status { display: inline-block; padding: 4px 12px; border-radius: 12px; color: white; font-size: 12px; }
        .status-completed { background-color: #10B981; }
        .status-missed { background-color: #EF4444; }
        .status-pending { background-color: #F59E0B; }
        .notes { background-color: #F3F4F6; padding: 15px; border-radius: 8px; margin-top: 10px; }
        .footer { margin-top: 40px; text-align: center; color: #6B7280; font-size: 12px; border-top: 1px solid #E5E7EB; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">Nutrition Details</div>
        <div class="subtitle">Generated by ${userName}</div>
      </div>
      
      <div class="section">
        <h1 style="font-size: 28px; margin-bottom: 10px;">${nutrition.foodItem || 'Nutrition Entry'}</h1>
        <span class="status ${nutrition.status === 'Completed' ? 'status-completed' : nutrition.status === 'Missed' ? 'status-missed' : 'status-pending'}">${nutrition.status}</span>
        <span style="margin-left: 10px; color: #6B7280;">${nutrition.mealType || ''}</span>
      </div>
      
      <div class="section">
        <div class="section-title">Nutritional Information</div>
        <div class="detail-row">
          <span class="label">Calories:</span>
          <span class="value">${nutrition.calories || 0} kcal</span>
        </div>
        <div class="detail-row">
          <span class="label">Protein:</span>
          <span class="value">${nutrition.protein || 0}g</span>
        </div>
        <div class="detail-row">
          <span class="label">Carbohydrates:</span>
          <span class="value">${nutrition.carbs || 0}g</span>
        </div>
        <div class="detail-row">
          <span class="label">Fats:</span>
          <span class="value">${nutrition.fats || 0}g</span>
        </div>
        <div class="detail-row">
          <span class="label">Fiber:</span>
          <span class="value">${nutrition.fiber || 0}g</span>
        </div>
        <div class="detail-row">
          <span class="label">Sugar:</span>
          <span class="value">${nutrition.sugar || 0}g</span>
        </div>
        <div class="detail-row">
          <span class="label">Sodium:</span>
          <span class="value">${nutrition.sodium || 0}mg</span>
        </div>
      </div>
      
      <div class="section">
        <div class="section-title">Additional Information</div>
        <div class="detail-row">
          <span class="label">Serving Size:</span>
          <span class="value">${nutrition.servingSize || 'N/A'}</span>
        </div>
        <div class="detail-row">
          <span class="label">Water Intake:</span>
          <span class="value">${nutrition.waterIntake ? nutrition.waterIntake + 'L' : 'N/A'}</span>
        </div>
        ${nutrition.date ? `
        <div class="detail-row">
          <span class="label">Date:</span>
          <span class="value">${new Date(nutrition.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
        </div>
        ` : ''}
      </div>
      
      ${nutrition.notes ? `
      <div class="section">
        <div class="section-title">Notes</div>
        <div class="notes">${nutrition.notes}</div>
      </div>
      ` : ''}
      
      <div class="footer">
        Generated from R-Fit Fitness App<br>
        ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
      </div>
    </body>
    </html>
  `;
  
  const blob = new Blob([htmlContent], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `nutrition-${nutrition.foodItem || 'details'}-${new Date().toISOString().split('T')[0]}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// Export Nutrition to CSV
export const exportNutritionToCsv = (nutrition, userName) => {
  const data = [
    ['Field', 'Value'],
    ['Food Item', nutrition.foodItem || ''],
    ['Status', nutrition.status || ''],
    ['Meal Type', nutrition.mealType || ''],
    ['Calories (kcal)', nutrition.calories || ''],
    ['Protein (g)', nutrition.protein || ''],
    ['Carbohydrates (g)', nutrition.carbs || ''],
    ['Fats (g)', nutrition.fats || ''],
    ['Fiber (g)', nutrition.fiber || ''],
    ['Sugar (g)', nutrition.sugar || ''],
    ['Sodium (mg)', nutrition.sodium || ''],
    ['Serving Size', nutrition.servingSize || ''],
    ['Water Intake (L)', nutrition.waterIntake || ''],
    ['Date', nutrition.date ? new Date(nutrition.date).toLocaleDateString() : ''],
    ['Notes', nutrition.notes || ''],
    ['Generated By', userName],
    ['Generated Date', new Date().toLocaleDateString()]
  ];
  
  let csvContent = '\uFEFF'; // BOM for UTF-8
  
  data.forEach(row => {
    const escapedRow = row.map(cell => {
      const cellStr = String(cell);
      if (cellStr.includes(',') || cellStr.includes('"') || cellStr.includes('\n')) {
        return `"${cellStr.replace(/"/g, '""')}"`;
      }
      return cellStr;
    });
    csvContent += escapedRow.join(',') + '\n';
  });
  
  downloadFile([csvContent], `nutrition-${nutrition.foodItem || 'details'}-${new Date().toISOString().split('T')[0]}.csv`, 'text/csv;charset=utf-8');
};
